# Generated by Django 4.2.4 on 2023-08-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category_product_purchasecard_purchaseline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone_number',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='purchasecard',
            name='status',
            field=models.CharField(choices=[('OPTION_ONE', 'Cancelled'), ('OPTION_TWO', 'Pending'), ('OPTION_THREE', 'Closed')], max_length=50),
        ),
    ]
